fbone/__init__.py
# -*- coding: utf-8 -*-

from app import create_app

fbone/app.py
# -*- coding: utf-8 -*-

import os

from flask import Flask, request, render_template
from flask.ext.login import login_required, current_user
from flask.ext.babel import Babel

from fbone.config import DefaultConfig
from fbone.modules.user import User, user
from fbone.modules.settings import settings
from fbone.modules.frontend import frontend
from fbone.modules.api import api
from fbone.modules.admin import admin
from fbone.extensions import db, mail, cache, login_manager
from fbone.utils import INSTANCE_FOLDER_PATH


# For import *
__all__ = ['create_app']

DEFAULT_BLUEPRINTS = (
    frontend,
    user,
    settings,
    api,
    admin,
)


def create_app(config=None, app_name=None, blueprints=None):
    """Create a Flask app."""

    if app_name is None:
        app_name = DefaultConfig.PROJECT
    if blueprints is None:
        blueprints = DEFAULT_BLUEPRINTS

    app = Flask(app_name, instance_path=INSTANCE_FOLDER_PATH, instance_relative_config=True)
    configure_app(app, config)
    configure_hook(app)
    configure_blueprints(app, blueprints)
    configure_extensions(app)
    configure_logging(app)
    configure_template_filters(app)
    configure_error_handlers(app)

    return app


def configure_app(app, config=None):
    """Different ways of configurations."""

    # http://flask.pocoo.org/docs/api/#configuration
    app.config.from_object(DefaultConfig)

    # http://flask.pocoo.org/docs/config/#instance-folders
    app.config.from_pyfile('production.cfg', silent=True)

    if config:
        app.config.from_object(config)

    # Use instance folder instead of env variables to make deployment easier.
    #app.config.from_envvar('%s_APP_CONFIG' % DefaultConfig.PROJECT.upper(), silent=True)


def configure_extensions(app):
    # flask-sqlalchemy
    db.init_app(app)

    # flask-mail
    mail.init_app(app)

    # flask-cache
    cache.init_app(app)

    # flask-babel
    babel = Babel(app)

    @babel.localeselector
    def get_locale():
        return request.accept_languages.best_match(DefaultConfig.LANGUAGES)

    # flask-login
    login_manager.login_view = 'frontend.login'
    login_manager.refresh_view = 'frontend.reauth'

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(id)
    login_manager.setup_app(app)


def configure_blueprints(app, blueprints):
    """Configure blueprints in views."""

    for blueprint in blueprints:
        app.register_blueprint(blueprint)


def configure_template_filters(app):

    @app.template_filter()
    def pretty_date(value):
        return pretty_date(value)

    @app.template_filter()
    def format_date(value, format='%Y-%m-%d'):
        return value.strftime(format)


def configure_logging(app):
    """Configure file(info) and email(error) logging."""

    if app.debug or app.testing:
        # Skip debug and test mode. Just check standard output.
        return

    import logging
    from logging.handlers import SMTPHandler

    # Set info level on logger, which might be overwritten by handers.
    # Suppress DEBUG messages.
    app.logger.setLevel(logging.INFO)

    info_log = os.path.join(app.config['LOG_FOLDER'], 'info.log')
    info_file_handler = logging.handlers.RotatingFileHandler(info_log, maxBytes=100000, backupCount=10)
    info_file_handler.setLevel(logging.INFO)
    info_file_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(info_file_handler)

    # Testing
    #app.logger.info("testing info.")
    #app.logger.warn("testing warn.")
    #app.logger.error("testing error.")

    mail_handler = SMTPHandler(app.config['MAIL_SERVER'],
                               app.config['MAIL_USERNAME'],
                               app.config['ADMINS'],
                               'O_ops... %s failed!' % app.config['PROJECT'],
                               (app.config['MAIL_USERNAME'],
                                app.config['MAIL_PASSWORD']))
    mail_handler.setLevel(logging.ERROR)
    mail_handler.setFormatter(logging.Formatter(
        '%(asctime)s %(levelname)s: %(message)s '
        '[in %(pathname)s:%(lineno)d]')
    )
    app.logger.addHandler(mail_handler)


def configure_hook(app):
    @app.before_request
    def before_request():
        pass

    # @app.context_processor
    # def ctx_processor():
    #     pass





def configure_error_handlers(app):

    @app.errorhandler(403)
    def forbidden_page(error):
        return render_template("errors/forbidden_page.html"), 403

    @app.errorhandler(404)
    def page_not_found(error):
        return render_template("errors/page_not_found.html"), 404

    @app.errorhandler(500)
    def server_error_page(error):
        return render_template("errors/server_error.html"), 500

fbone/modules/__init__.py
# -*- coding: utf-8 -*-

fbone/modules/admin/__init__.py
# -*- coding: utf-8 -*-

from .views import admin

fbone/modules/admin/views.py
# -*- coding: utf-8 -*-

import os

from flask import Blueprint, render_template, request, flash, current_app, send_from_directory, redirect, url_for
from flask.ext.login import login_required
from flask.ext.babel import Babel
from werkzeug import secure_filename

from fbone.decorators import admin_required
from fbone.modules.user import User
from .forms import UserForm, EditTranslationForm, UploadLogoForm


admin = Blueprint('admin', __name__, url_prefix='/admin')

@admin.route('/')
@login_required
@admin_required
def index():
    users = User.query.all()
    logo_form = UploadLogoForm()
    return render_template('admin/index.html', users=users, active='index',logo_form=logo_form)


@admin.route('/users')
@login_required
@admin_required
def users():
    users = User.query.all()
    return render_template('admin/users.html', users=users, active='users')


@admin.route('/user/<int:user_id>', methods=['GET', 'POST'])
@login_required
@admin_required
def user(user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    form = UserForm(obj=user, next=request.args.get('next'))

    if form.validate_on_submit():
        form.save(user)

        flash('User updated.', 'success')

    return render_template('admin/user.html', user=user, form=form)


@admin.route('/translation/edit/<language>', methods=['POST','GET'])
@login_required
@admin_required
def edit_translation(language):
    form = EditTranslationForm(language = language)
    if form.validate_on_submit():
        file = request.files[form.file.name]
        if file:
            filename = secure_filename(file.filename)
            file.save(os.path.join(current_app.config['TRANSLATIONS_FOLDER'], language,current_app.config['TRANSLATIONS_PATH'],current_app.config['TRANSALTIONS_FILE']))
            os.system("pybabel compile -f -d fbone/translations")
            flash("Translation File has been uploaded")
            return redirect(url_for('admin.edit_translation',language=language))
    return render_template('admin/translation.html',form=form)

@admin.route('/translations', methods=['GET'])
@login_required
@admin_required
def translations():
    babel  = Babel(current_app)
    languages = babel.list_translations()
    return render_template('admin/translations.html',languages = languages)

@admin.route('/translation/<language>', methods=['GET'])
@login_required
@admin_required
def existing_translation(language):
    return send_from_directory(os.path.join(current_app.config['TRANSLATIONS_FOLDER'],language,current_app.config['TRANSLATIONS_PATH']),current_app.config['TRANSALTIONS_FILE'])


@admin.route('/logo', methods=['POST'])
@login_required
@admin_required
def upload_logo():
    form = UploadLogoForm()
    if form.validate_on_submit():
        file = request.files[form.file.name]
        if file:
            filename = secure_filename(file.filename)
            file.save(current_app.config['LOGO_FILE'])
            flash("Logo File has been uploaded")
            return redirect(url_for('admin.index'))

fbone/modules/api/__init__.py
# -*- coding: utf-8 -*-

from .views import api

fbone/modules/api/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, current_app, request, jsonify
from flask.ext.login import login_user, current_user, logout_user

from ..user import User


api = Blueprint('api', __name__, url_prefix='/api')


@api.route('/login', methods=['POST'])
def login():
    if current_user.is_authenticated():
        return jsonify(flag='success')

    username = request.form.get('username')
    password = request.form.get('password')
    if username and password:
        user, authenticated = User.authenticate(username, password)
        if user and authenticated:
            if login_user(user, remember='y'):
                return jsonify(flag='success')

    current_app.logger.debug('login(api) failed, username: %s.' % username)
    return jsonify(flag='fail', msg='Sorry, try again.')


@api.route('/logout')
def logout():
    if current_user.is_authenticated():
        logout_user()
    return jsonify(flag='success', msg='Logged out.')

fbone/modules/frontend/__init__.py
# -*- coding: utf-8 -*-

from .views import frontend

fbone/modules/frontend/views.py
# -*- coding: utf-8 -*-

from uuid import uuid4

from flask import (Blueprint, render_template, current_app, request,
                   flash, url_for, redirect, session, abort)
from flask.ext.mail import Message
from flask.ext.login import login_required, login_user, current_user, logout_user, confirm_login, login_fresh
from flask.ext.babel import gettext as _

from fbone.modules.user import User, UserDetail
from fbone.extensions import  mail, login_manager
from .forms import SignupForm, LoginForm, RecoverPasswordForm, ReauthForm, ChangePasswordForm, CreateProfileForm


frontend = Blueprint('frontend', __name__)


@frontend.route('/create_profile', methods=['GET', 'POST'])
def create_profile():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = CreateProfileForm(name=request.args.get('name'),
            email=request.args.get('email'),
            openid=request.args.get('openid'))

    if form.validate_on_submit():
        form.create_profile()

        if login_user(user):
            return redirect(url_for('user.index'))

    return render_template('frontend/create_profile.html', form=form)


@frontend.route('/')
def index():
    current_app.logger.debug('debug')

    if current_user.is_authenticated():
        return redirect(url_for('user.index'))
    return render_template('index.html')


@frontend.route('/search')
def search():
    keywords = request.args.get('keywords', '').strip()
    pagination = None
    if keywords:
        page = int(request.args.get('page', 1))
        pagination = User.search(keywords).paginate(page, 1)
    else:
        flash(_('Please input keyword(s)'), 'error')
    return render_template('frontend/search.html', pagination=pagination, keywords=keywords)


@frontend.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = LoginForm(login=request.args.get('login', None),
                     next=request.args.get('next', None))

    if form.validate_on_submit():
        user, authenticated = User.authenticate(form.login.data,
                                    form.password.data)

        if user and authenticated:
            remember = request.form.get('remember') == 'y'
            if login_user(user, remember=remember):
                flash(_("Logged in"), 'success')
            return redirect(form.next.data or url_for('user.index'))
        else:
            flash(_('Sorry, invalid login'), 'error')

    return render_template('frontend/login.html', form=form)


@frontend.route('/reauth', methods=['GET', 'POST'])
@login_required
def reauth():
    form = ReauthForm(next=request.args.get('next'))

    if request.method == 'POST':
        user, authenticated = User.authenticate(current_user.name,
                                    form.password.data)
        if user and authenticated:
            confirm_login()
            current_app.logger.debug('reauth: %s' % session['_fresh'])
            flash(_('Reauthenticated.'), 'success')
            return redirect('/change_password')

        flash(_('Password is wrong.'), 'error')
    return render_template('frontend/reauth.html', form=form)


@frontend.route('/logout')
@login_required
def logout():
    logout_user()
    flash(_('Logged out'), 'success')
    return redirect(url_for('frontend.index'))


@frontend.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated():
        return redirect(url_for('user.index'))

    form = SignupForm(next=request.args.get('next'))

    if form.validate_on_submit():
        user = form.signup()

        if login_user(user):
            return redirect(form.next.data or url_for('user.index'))

    return render_template('frontend/signup.html', form=form)


@frontend.route('/change_password', methods=['GET', 'POST'])
def change_password():
    user = None
    if current_user.is_authenticated():
        if not login_fresh():
            return login_manager.needs_refresh()
        user = current_user
    elif 'activation_key' in request.values and 'email' in request.values:
        activation_key = request.values['activation_key']
        email = request.values['email']
        user = User.query.filter_by(activation_key=activation_key) \
                         .filter_by(email=email).first()

    if user is None:
        abort(403)

    form = ChangePasswordForm(activation_key=user.activation_key)

    if form.validate_on_submit():
        user.change_password()

        flash(_("Your password has been changed, please log in again"),
              "success")
        return redirect(url_for("frontend.login"))

    return render_template("frontend/change_password.html", form=form)


@frontend.route('/reset_password', methods=['GET', 'POST'])
def reset_password():
    form = RecoverPasswordForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if user:
            flash('Please see your email for instructions on '
                  'how to access your account', 'success')

            user.recover_password()

            url = url_for('frontend.change_password', email=user.email, activation_key=user.activation_key, _external=True)
            html = render_template('macros/_reset_password.html', project=current_app.config['PROJECT'], username=user.name, url=url)
            message = Message(subject='Reset your password in ' + current_app.config['PROJECT'], html=html, recipients=[user.email])
            mail.send(message)

            return render_template('frontend/reset_password.html', form=form)
        else:
            flash(_('Sorry, no user found for that email address'), 'error')

    return render_template('frontend/reset_password.html', form=form)


@frontend.route('/help')
def help():
    return render_template('frontend/footers/help.html', active="help")

fbone/modules/settings/__init__.py
# -*- coding: utf-8 -*-

from .views import settings

fbone/modules/settings/views.py
# -*- coding: utf-8 -*-

import os
import hashlib
from datetime import datetime

from flask import Blueprint, render_template, current_app, request, flash
from flask.ext.login import login_required, current_user

from fbone.modules.user import User
from fbone.utils import allowed_file, make_dir
from .forms import ProfileForm, PasswordForm


settings = Blueprint('settings', __name__, url_prefix='/settings')


@settings.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    user = User.query.filter_by(name=current_user.name).first_or_404()
    form = ProfileForm(obj=user.user_detail,
            email=current_user.email,
            role_code=current_user.role_code,
            status_code=current_user.status_code,
            next=request.args.get('next'))

    if form.validate_on_submit():

        form.create_profile(request,user)

        flash('Public profile updated.', 'success')

    return render_template('settings/profile.html', user=user,
            active="profile", form=form)


@settings.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    user = User.query.filter_by(name=current_user.name).first_or_404()
    form = PasswordForm(next=request.args.get('next'))

    if form.validate_on_submit():
        form.update_password(user)

        flash(_('Password updated.'), 'success')

    return render_template('settings/password.html', user=user,
            active="password", form=form)

fbone/modules/user/__init__.py
# -*- coding: utf-8 -*-

from .models import UserDetail, User
from .views import user
from .constants import USER_ROLE, ADMIN, USER, USER_STATUS, NEW, ACTIVE

fbone/templates/layouts/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>{% block title %}{{ page_title|default(_('Project')) }}{% endblock %}</title>
    <meta name="description" content="Fbone (Flask bone) is a Flask (Python microframework) template/bootstrap/boilerplate application.">
    <meta name="author" content="Wilson Xu">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="Shortcut Icon" href="{{ url_for('static', filename='favicon.png') }}" type="image/x-icon">
    {% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% endblock %}

    {% block css_style %}
    {% endblock %}

    {% block js_top %}
        <script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
        <script type="text/javascript">
          var $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
        </script>
    {% endblock %}
</head>

<body>
    {% include "macros/_ask_user_to_update_ie.html" %}

    <div id='wrap'>
        {% block topbar %}
        <div class="navbar">
<!--             <div class="navbar-inner">
                <div class="container">
                    <a class='brand' href='{{ url_for('frontend.index') }}'><img class='logo' src="{{ url_for('static', filename='img/logo.png') }}" /></a>

                    {% if current_user.is_authenticated() %}
                    <form class="navbar-search pull-left" action="{{ url_for('frontend.search') }}">
                        <input type='text' class="search-query" name='keywords' value='{{ keywords|default('') }}' placeholder='Search' />
                    </form>
                    <div class="nav-collapse collapse pull-right">
                        <ul class="nav">
                            {% if current_user.is_admin() %}
                            <li><a href="{{ url_for('admin.index') }}">{{ current_user.name }}</a></li>
                            {% else %}
                            <li><a href="{{ url_for('user.index') }}">{{ current_user.name }}</a></li>
                            {% endif %}
                            <li><a href="{{ url_for('settings.profile') }}">{{_('Settings')}}</a></li>
                            <li><a href="{{ url_for('frontend.logout') }}">{{_('Log out')}}</a></li>
                        </ul>
                    </div>
                    {% else %}
                    <div class="nav-collapse collapse pull-right">
                        <ul class="nav">
                            <li><span><a class="btn btn-success" href="{{ url_for('frontend.signup') }}"><strong>{{_('Sign up')}}</strong></a></span></li>
                            <li><a href="{{ url_for('frontend.login') }}">{{_('Sign in')}}</a></li>
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </div> -->
        </div>
        {% endblock %}

        {% block flash_message %}
            {% with messages = get_flashed_messages(with_categories=True) %}
                {% if messages %}
                <div class="container">
                    <div id='flash_message_container'>
                        {% for category, msg in messages %}
                            <div class="alert alert-{{ category }}">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                {{ msg }}
                            </div>
                        {% endfor %}
                    </div>
                </div>
                {% endif %}
            {% endwith %}
        {% endblock %}

        {% block container %}
        <div class="container">

            {% block top %}
                {% if tabs %}
                <div>
                    <ul class="nav nav-tabs">
                        {% for tab, link in tabs %}
                        <li class="{% if active == tab %}active{% endif %}">
                            <a href="{{ link }}">{{ tab|capitalize }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif %}
            {% endblock %}

            {% block body %}
            {% endblock %}

        </div> -->
        {% endblock %}
        <div id="push"></div>
    </div>

    <footer>
<!--         <ul class="footer-links">
            <li>{{_('&copy;')}}</li>
            <li><a href='https://github.com/frankV/manekineko'>{{_('About')}}</a></li>
            <li class="muted">&middot;</li>
            <li><a href='{{ url_for('frontend.help') }}'>{{_('Help')}}</a></li>
            <li class="muted">&middot;</li>
            <li><a href='#'>{{_('Terms')}}</a></li>
        </ul> -->
    </footer>


    {% block js_btm %}
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/plugins.js') }}"></script>
    <script src="{{ url_for('static', filename='js/vendor/bootstrap.js') }}"></script>
    <script src="{{ url_for('static', filename='js/main.js') }}"></script>
    {% endblock %}

    {% block extra_js %}
    {% endblock %}

    {% block ga %}
    {% include "macros/_google_analytics.html" %}
    {% endblock %}
</body>
</html>